netbox/dcim/urls.py
from django.urls import path

from extras.views import ImageAttachmentEditView, ObjectChangeLogView, ObjectJournalView
from ipam.views import ServiceEditView
from utilities.views import SlugRedirectView
from . import views
from .models import *

app_name = 'dcim'
urlpatterns = [

    # Regions
    path('regions/', views.RegionListView.as_view(), name='region_list'),
    path('regions/add/', views.RegionEditView.as_view(), name='region_add'),
    path('regions/import/', views.RegionBulkImportView.as_view(), name='region_import'),
    path('regions/edit/', views.RegionBulkEditView.as_view(), name='region_bulk_edit'),
    path('regions/delete/', views.RegionBulkDeleteView.as_view(), name='region_bulk_delete'),
    path('regions/<int:pk>/', views.RegionView.as_view(), name='region'),
    path('regions/<int:pk>/edit/', views.RegionEditView.as_view(), name='region_edit'),
    path('regions/<int:pk>/delete/', views.RegionDeleteView.as_view(), name='region_delete'),
    path('regions/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='region_changelog', kwargs={'model': Region}),

    # Site groups
    path('site-groups/', views.SiteGroupListView.as_view(), name='sitegroup_list'),
    path('site-groups/add/', views.SiteGroupEditView.as_view(), name='sitegroup_add'),
    path('site-groups/import/', views.SiteGroupBulkImportView.as_view(), name='sitegroup_import'),
    path('site-groups/edit/', views.SiteGroupBulkEditView.as_view(), name='sitegroup_bulk_edit'),
    path('site-groups/delete/', views.SiteGroupBulkDeleteView.as_view(), name='sitegroup_bulk_delete'),
    path('site-groups/<int:pk>/', views.SiteGroupView.as_view(), name='sitegroup'),
    path('site-groups/<int:pk>/edit/', views.SiteGroupEditView.as_view(), name='sitegroup_edit'),
    path('site-groups/<int:pk>/delete/', views.SiteGroupDeleteView.as_view(), name='sitegroup_delete'),
    path('site-groups/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='sitegroup_changelog', kwargs={'model': SiteGroup}),

    # Sites
    path('sites/', views.SiteListView.as_view(), name='site_list'),
    path('sites/add/', views.SiteEditView.as_view(), name='site_add'),
    path('sites/import/', views.SiteBulkImportView.as_view(), name='site_import'),
    path('sites/edit/', views.SiteBulkEditView.as_view(), name='site_bulk_edit'),
    path('sites/delete/', views.SiteBulkDeleteView.as_view(), name='site_bulk_delete'),
    path('sites/<int:pk>/', views.SiteView.as_view(), name='site'),
    path('sites/<slug:slug>/', SlugRedirectView.as_view(), kwargs={'model': Site}),
    path('sites/<int:pk>/edit/', views.SiteEditView.as_view(), name='site_edit'),
    path('sites/<int:pk>/delete/', views.SiteDeleteView.as_view(), name='site_delete'),
    path('sites/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='site_changelog', kwargs={'model': Site}),
    path('sites/<int:pk>/journal/', ObjectJournalView.as_view(), name='site_journal', kwargs={'model': Site}),
    path('sites/<int:object_id>/images/add/', ImageAttachmentEditView.as_view(), name='site_add_image', kwargs={'model': Site}),

    # Locations
    path('locations/', views.LocationListView.as_view(), name='location_list'),
    path('locations/add/', views.LocationEditView.as_view(), name='location_add'),
    path('locations/import/', views.LocationBulkImportView.as_view(), name='location_import'),
    path('locations/edit/', views.LocationBulkEditView.as_view(), name='location_bulk_edit'),
    path('locations/delete/', views.LocationBulkDeleteView.as_view(), name='location_bulk_delete'),
    path('locations/<int:pk>/', views.LocationView.as_view(), name='location'),
    path('locations/<int:pk>/edit/', views.LocationEditView.as_view(), name='location_edit'),
    path('locations/<int:pk>/delete/', views.LocationDeleteView.as_view(), name='location_delete'),
    path('locations/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='location_changelog', kwargs={'model': Location}),
    path('locations/<int:object_id>/images/add/', ImageAttachmentEditView.as_view(), name='location_add_image', kwargs={'model': Location}),

    # Rack roles
    path('rack-roles/', views.RackRoleListView.as_view(), name='rackrole_list'),
    path('rack-roles/add/', views.RackRoleEditView.as_view(), name='rackrole_add'),
    path('rack-roles/import/', views.RackRoleBulkImportView.as_view(), name='rackrole_import'),
    path('rack-roles/edit/', views.RackRoleBulkEditView.as_view(), name='rackrole_bulk_edit'),
    path('rack-roles/delete/', views.RackRoleBulkDeleteView.as_view(), name='rackrole_bulk_delete'),
    path('rack-roles/<int:pk>/', views.RackRoleView.as_view(), name='rackrole'),
    path('rack-roles/<int:pk>/edit/', views.RackRoleEditView.as_view(), name='rackrole_edit'),
    path('rack-roles/<int:pk>/delete/', views.RackRoleDeleteView.as_view(), name='rackrole_delete'),
    path('rack-roles/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackrole_changelog', kwargs={'model': RackRole}),

    # Rack reservations
    path('rack-reservations/', views.RackReservationListView.as_view(), name='rackreservation_list'),
    path('rack-reservations/add/', views.RackReservationEditView.as_view(), name='rackreservation_add'),
    path('rack-reservations/import/', views.RackReservationImportView.as_view(), name='rackreservation_import'),
    path('rack-reservations/edit/', views.RackReservationBulkEditView.as_view(), name='rackreservation_bulk_edit'),
    path('rack-reservations/delete/', views.RackReservationBulkDeleteView.as_view(), name='rackreservation_bulk_delete'),
    path('rack-reservations/<int:pk>/', views.RackReservationView.as_view(), name='rackreservation'),
    path('rack-reservations/<int:pk>/edit/', views.RackReservationEditView.as_view(), name='rackreservation_edit'),
    path('rack-reservations/<int:pk>/delete/', views.RackReservationDeleteView.as_view(), name='rackreservation_delete'),
    path('rack-reservations/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rackreservation_changelog', kwargs={'model': RackReservation}),
    path('rack-reservations/<int:pk>/journal/', ObjectJournalView.as_view(), name='rackreservation_journal', kwargs={'model': RackReservation}),

    # Racks
    path('racks/', views.RackListView.as_view(), name='rack_list'),
    path('rack-elevations/', views.RackElevationListView.as_view(), name='rack_elevation_list'),
    path('racks/add/', views.RackEditView.as_view(), name='rack_add'),
    path('racks/import/', views.RackBulkImportView.as_view(), name='rack_import'),
    path('racks/edit/', views.RackBulkEditView.as_view(), name='rack_bulk_edit'),
    path('racks/delete/', views.RackBulkDeleteView.as_view(), name='rack_bulk_delete'),
    path('racks/<int:pk>/', views.RackView.as_view(), name='rack'),
    path('racks/<int:pk>/edit/', views.RackEditView.as_view(), name='rack_edit'),
    path('racks/<int:pk>/delete/', views.RackDeleteView.as_view(), name='rack_delete'),
    path('racks/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='rack_changelog', kwargs={'model': Rack}),
    path('racks/<int:pk>/journal/', ObjectJournalView.as_view(), name='rack_journal', kwargs={'model': Rack}),
    path('racks/<int:object_id>/images/add/', ImageAttachmentEditView.as_view(), name='rack_add_image', kwargs={'model': Rack}),

    # Manufacturers
    path('manufacturers/', views.ManufacturerListView.as_view(), name='manufacturer_list'),
    path('manufacturers/add/', views.ManufacturerEditView.as_view(), name='manufacturer_add'),
    path('manufacturers/import/', views.ManufacturerBulkImportView.as_view(), name='manufacturer_import'),
    path('manufacturers/edit/', views.ManufacturerBulkEditView.as_view(), name='manufacturer_bulk_edit'),
    path('manufacturers/delete/', views.ManufacturerBulkDeleteView.as_view(), name='manufacturer_bulk_delete'),
    path('manufacturers/<int:pk>/', views.ManufacturerView.as_view(), name='manufacturer'),
    path('manufacturers/<int:pk>/edit/', views.ManufacturerEditView.as_view(), name='manufacturer_edit'),
    path('manufacturers/<int:pk>/delete/', views.ManufacturerDeleteView.as_view(), name='manufacturer_delete'),
    path('manufacturers/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='manufacturer_changelog', kwargs={'model': Manufacturer}),

    # Device types
    path('device-types/', views.DeviceTypeListView.as_view(), name='devicetype_list'),
    path('device-types/add/', views.DeviceTypeEditView.as_view(), name='devicetype_add'),
    path('device-types/import/', views.DeviceTypeImportView.as_view(), name='devicetype_import'),
    path('device-types/edit/', views.DeviceTypeBulkEditView.as_view(), name='devicetype_bulk_edit'),
    path('device-types/delete/', views.DeviceTypeBulkDeleteView.as_view(), name='devicetype_bulk_delete'),
    path('device-types/<int:pk>/', views.DeviceTypeView.as_view(), name='devicetype'),
    path('device-types/<int:pk>/edit/', views.DeviceTypeEditView.as_view(), name='devicetype_edit'),
    path('device-types/<int:pk>/delete/', views.DeviceTypeDeleteView.as_view(), name='devicetype_delete'),
    path('device-types/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='devicetype_changelog', kwargs={'model': DeviceType}),
    path('device-types/<int:pk>/journal/', ObjectJournalView.as_view(), name='devicetype_journal', kwargs={'model': DeviceType}),

    # Console port templates
    path('console-port-templates/add/', views.ConsolePortTemplateCreateView.as_view(), name='consoleporttemplate_add'),
    path('console-port-templates/edit/', views.ConsolePortTemplateBulkEditView.as_view(), name='consoleporttemplate_bulk_edit'),
    path('console-port-templates/rename/', views.ConsolePortTemplateBulkRenameView.as_view(), name='consoleporttemplate_bulk_rename'),
    path('console-port-templates/delete/', views.ConsolePortTemplateBulkDeleteView.as_view(), name='consoleporttemplate_bulk_delete'),

netbox/netbox/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
from django.views.static import serve
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
from netbox.api.views import APIRootView, StatusView
from netbox.views import HomeView, StaticMediaFailureView, SearchView
from users.views import LoginView, LogoutView
from .admin import admin_site


openapi_info = openapi.Info(
    title="NetBox API",
    default_version='v2',
    description="API to access NetBox",
    terms_of_service="https://github.com/netbox-community/netbox",
    license=openapi.License(name="Apache v2 License"),
)

schema_view = get_schema_view(
    openapi_info,
    validators=['flex', 'ssv'],
    public=True,
)

_patterns = [

    # Base views
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),

    # Login/logout
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Apps
    path('circuits/', include('circuits.urls')),
    path('dcim/', include('dcim.urls')),
    path('extras/', include('extras.urls')),
    path('ipam/', include('ipam.urls')),
    path('secrets/', include('secrets.urls')),
    path('tenancy/', include('tenancy.urls')),
    path('user/', include('users.urls')),
    path('virtualization/', include('virtualization.urls')),

    # API
    path('api/', APIRootView.as_view(), name='api-root'),
    path('api/circuits/', include('circuits.api.urls')),
    path('api/dcim/', include('dcim.api.urls')),
    path('api/extras/', include('extras.api.urls')),
    path('api/ipam/', include('ipam.api.urls')),
    path('api/secrets/', include('secrets.api.urls')),
    path('api/tenancy/', include('tenancy.api.urls')),
    path('api/users/', include('users.api.urls')),
    path('api/virtualization/', include('virtualization.api.urls')),
    path('api/status/', StatusView.as_view(), name='api-status'),
    path('api/docs/', schema_view.with_ui('swagger'), name='api_docs'),
    path('api/redoc/', schema_view.with_ui('redoc'), name='api_redocs'),
    re_path(r'^api/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(), name='schema_swagger'),

    # Serving static media in Django to pipe it through LoginRequiredMiddleware
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('media-failure/', StaticMediaFailureView.as_view(), name='media_failure'),

    # Plugins
    path('plugins/', include((plugin_patterns, 'plugins'))),
    path('api/plugins/', include((plugin_api_patterns, 'plugins-api'))),

    # Admin
    path('admin/background-tasks/', include('django_rq.urls')),
    path('admin/plugins/', include(plugin_admin_patterns)),
    path('admin/', admin_site.urls),
]


if settings.DEBUG:
    import debug_toolbar
    _patterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

if settings.METRICS_ENABLED:
    _patterns += [
        path('', include('django_prometheus.urls')),
    ]

# Prepend BASE_PATH
urlpatterns = [
    path('{}'.format(settings.BASE_PATH), include(_patterns))
]

handler500 = 'netbox.views.server_error'

netbox/users/api/urls.py
from netbox.api import OrderedDefaultRouter
from . import views


router = OrderedDefaultRouter()
router.APIRootView = views.UsersRootView

# Users and groups
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)

# Permissions
router.register('permissions', views.ObjectPermissionViewSet)

# User preferences
router.register('config', views.UserConfigViewSet, basename='userconfig')

app_name = 'users-api'
urlpatterns = router.urls

netbox/users/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('preferences/', views.UserConfigView.as_view(), name='preferences'),
    path('password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('api-tokens/', views.TokenListView.as_view(), name='token_list'),
    path('api-tokens/add/', views.TokenEditView.as_view(), name='token_add'),
    path('api-tokens/<int:pk>/edit/', views.TokenEditView.as_view(), name='token_edit'),
    path('api-tokens/<int:pk>/delete/', views.TokenDeleteView.as_view(), name='token_delete'),
    path('user-key/', views.UserKeyView.as_view(), name='userkey'),
    path('user-key/edit/', views.UserKeyEditView.as_view(), name='userkey_edit'),
    path('session-key/delete/', views.SessionKeyDeleteView.as_view(), name='sessionkey_delete'),

]

netbox/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm as DjangoPasswordChangeForm

from utilities.forms import BootstrapMixin, DateTimePicker
from .models import Token


class LoginForm(BootstrapMixin, AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['placeholder'] = ''
        self.fields['password'].widget.attrs['placeholder'] = ''


class PasswordChangeForm(BootstrapMixin, DjangoPasswordChangeForm):
    pass


class TokenForm(BootstrapMixin, forms.ModelForm):
    key = forms.CharField(
        required=False,
        help_text="If no key is provided, one will be generated automatically."
    )

    class Meta:
        model = Token
        fields = [
            'key', 'write_enabled', 'expires', 'description',
        ]
        widgets = {
            'expires': DateTimePicker(),
        }

netbox/users/api/views.py
from django.contrib.auth.models import Group, User
from django.db.models import Count
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.routers import APIRootView
from rest_framework.viewsets import ViewSet

from netbox.api.views import ModelViewSet
from users import filtersets
from users.models import ObjectPermission, UserConfig
from utilities.querysets import RestrictedQuerySet
from utilities.utils import deepmerge
from . import serializers


class UsersRootView(APIRootView):
    """
    Users API root view
    """
    def get_view_name(self):
        return 'Users'


#
# Users and groups
#

class UserViewSet(ModelViewSet):
    queryset = RestrictedQuerySet(model=User).prefetch_related('groups').order_by('username')
    serializer_class = serializers.UserSerializer
    filterset_class = filtersets.UserFilterSet


class GroupViewSet(ModelViewSet):
    queryset = RestrictedQuerySet(model=Group).annotate(user_count=Count('user')).order_by('name')
    serializer_class = serializers.GroupSerializer
    filterset_class = filtersets.GroupFilterSet


#
# ObjectPermissions
#

class ObjectPermissionViewSet(ModelViewSet):
    queryset = ObjectPermission.objects.prefetch_related('object_types', 'groups', 'users')
    serializer_class = serializers.ObjectPermissionSerializer
    filterset_class = filtersets.ObjectPermissionFilterSet


#
# User preferences
#

class UserConfigViewSet(ViewSet):
    """
    An API endpoint via which a user can update his or her own UserConfig data (but no one else's).
    """
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        return UserConfig.objects.filter(user=self.request.user)

    def list(self, request):
        """
        Return the UserConfig for the currently authenticated User.
        """
        userconfig = self.get_queryset().first()

        return Response(userconfig.data)

    def patch(self, request):
        """
        Update the UserConfig for the currently authenticated User.
        """
        # TODO: How can we validate this data?
        userconfig = self.get_queryset().first()
        userconfig.data = deepmerge(userconfig.data, request.data)
        userconfig.save()

        return Response(userconfig.data)

netbox/templates/users/api_tokens.html
{% extends 'users/base.html' %}
{% load helpers %}

{% block title %}API Tokens{% endblock %}

{% block usercontent %}
    <div class="row">
        <div class="col-md-12">
            {% for token in tokens %}
                <div class="panel panel-{% if token.is_expired %}danger{% else %}default{% endif %}">
                    <div class="panel-heading">
                        <div class="pull-right noprint">
                            <a class="btn btn-xs btn-success copy-token" data-clipboard-target="#token_{{ token.pk }}">Copy</a>
                            <a href="{% url 'user:token_edit' pk=token.pk %}" class="btn btn-xs btn-warning">Edit</a>
                            <a href="{% url 'user:token_delete' pk=token.pk %}" class="btn btn-xs btn-danger">Delete</a>
                        </div>
                        <i class="mdi mdi-key"></i>
                        <samp><span id="token_{{ token.pk }}">{{ token.key }}</span></samp>
                        {% if token.is_expired %}
                            <span class="label label-danger">Expired</span>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-4">
                                <small class="text-muted">Created</small><br />
                                {{ token.created|annotated_date }}
                            </div>
                            <div class="col-md-4">
                                <small class="text-muted">Expires</small><br />
                                {% if token.expires %}
                                    {{ token.expires|annotated_date }}
                                {% else %}
                                    <span>Never</span>
                                {% endif %}
                            </div>
                            <div class="col-md-4">
                                <small class="text-muted">Create/edit/delete operations</small><br />
                                {% if token.write_enabled %}
                                    <span class="label label-success">Enabled</span>
                                {% else %}
                                    <span class="label label-danger">Disabled</span>
                                {% endif %}
                            </div>
                        </div>
                        {% if token.description %}
                            <br /><span>{{ token.description }}</span>
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <p>You do not have any API tokens.</p>
            {% endfor %}
            <a href="{% url 'user:token_add' %}" class="btn btn-primary">
                <span class="mdi mdi-plus-thick" aria-hidden="true"></span>
                Add a token
            </a>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
new ClipboardJS('.copy-token');
</script>
{% endblock %}

netbox/templates/users/base.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
        <h1>{% block title %}{% endblock %}</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-3 col-md-2 col-md-offset-1">
        <ul class="nav nav-pills nav-stacked">
            <li{% if active_tab == "profile" %} class="active"{% endif %}>
                <a href="{% url 'user:profile' %}">Profile</a>
            </li>
            <li{% if active_tab == "preferences" %} class="active"{% endif %}>
                <a href="{% url 'user:preferences' %}">Preferences</a>
            </li>
            {% if not request.user.ldap_username %}
                <li{% if active_tab == "change_password" %} class="active"{% endif %}>
                    <a href="{% url 'user:change_password' %}">Change Password</a>
                </li>
            {% endif %}
            <li{% if active_tab == "api_tokens" %} class="active"{% endif %}>
                <a href="{% url 'user:token_list' %}">API Tokens</a>
            </li>
            <li{% if active_tab == "userkey" %} class="active"{% endif %}>
                <a href="{% url 'user:userkey' %}">User Key</a>
            </li>
        </ul>
    </div>
	<div class="col-sm-9 col-md-8">
        {% block usercontent %}{% endblock %}
	</div>
</div>
{% endblock %}

netbox/templates/users/change_password.html
{% extends 'users/base.html' %}
{% load form_helpers %}

{% block title %}Change Password{% endblock %}

{% block usercontent %}
    <form action="." method="post" class="form form-horizontal col-md-10 col-md-offset-1">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="panel panel-danger">
                <div class="panel-heading"><strong>Errors</strong></div>
                <div class="panel-body">
                    {{ form.non_field_errors }}
                </div>
            </div>
        {% endif %}
        <div class="panel panel-default">
            <div class="panel-heading"><strong>Password</strong></div>
            <div class="panel-body">
                {% render_field form.old_password %}
                {% render_field form.new_password1 %}
                {% render_field form.new_password2 %}
            </div>
        </div>
        <div class="text-right">
            <button type="submit" name="_update" class="btn btn-primary">Update</button>
            <a href="{% url 'user:profile' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
{% endblock %}

netbox/templates/users/profile.html
{% extends 'users/base.html' %}
{% load helpers %}

{% block title %}User Profile{% endblock %}

{% block usercontent %}
    <small class="text-muted">User login</small>
    <h5>{{ request.user.username }}</h5>
    <small class="text-muted">Full name</small>
    <h5>{{ request.user.first_name }} {{ request.user.last_name }}</h5>
    <small class="text-muted">Email</small>
    <h5>{{ request.user.email }}</h5>
    <small class="text-muted">Registered</small>
    <h5>{{ request.user.date_joined|annotated_date }}</h5>
    <small class="text-muted">Groups</small>
    <h5>{{ request.user.groups.all|join:', ' }}</h5>
    <small class="text-muted">Admin access</small>
    <h5>{{ request.user.is_staff|yesno|capfirst }}</h5>
{% endblock %}

netbox/templates/users/sessionkey_delete.html
{% extends 'generic/object_delete.html' %}

{% block message %}
    <p>Are you sure you want to delete your session key?</p>
{% endblock %}

netbox/templates/users/userkey.html
{% extends 'users/base.html' %}
{% load helpers %}

{% block title %}User Key{% endblock %}

{% block usercontent %}
    {% if object %}
        <div class="pull-right noprint">
            <a href="{% url 'user:userkey_edit' %}" class="btn btn-warning">
                <span class="mdi mdi-pencil" aria-hidden="true"></span>
                Edit user key
            </a>
        </div>
        <h4>
            Your user key is:
            {% if object.is_active %}
                <span class="label label-success">Active</span>
            {% else %}
                <span class="label label-danger">Inactive</span>
            {% endif %}
        </h4>
        <p>
            <small class="text-muted">
              Created {{ object.created|annotated_date }} &middot;
              Updated {{ object.last_updated|annotated_date }} ({{ object.last_updated|timesince }} ago)
        </p>
        {% if not object.is_active %}
            <div class="alert alert-warning" role="alert">
                <i class="mdi mdi-alert"></i>
                Your user key is inactive. Ask an administrator to enable it for you.
            </div>
        {% endif %}
        <pre>{{ object.public_key }}</pre>
        <hr />
        {% if object.session_key %}
            <div class="pull-right noprint">
                <a href="{% url 'user:sessionkey_delete' %}" class="btn btn-danger">
                    <span class="mdi mdi-trash-can-outline" aria-hidden="true"></span>
                    Delete session key
                </a>
            </div>
            <h4>Session key: <span class="label label-success">Active</span></h4>
            <small class="text-muted">Created {{ object.session_key.created|annotated_date }}</small>
        {% else %}
            <h4>No active session key</h4>
        {% endif %}
    {% else %}
        <p>You don't have a user key on file.</p>
        <p>
            <a href="{% url 'user:userkey_edit' %}" class="btn btn-primary">
                <span class="mdi mdi-plus-thick" aria-hidden="true"></span>
                Create a User Key
            </a>
        </p>
    {% endif %}
{% endblock %}

netbox/templates/users/userkey_edit.html
{% extends 'users/base.html' %}
{% load static %}
{% load form_helpers %}

{% block title %}User Key{% endblock %}

{% block usercontent %}
    {% if object.is_active %}
        <div class="alert alert-danger" role="alert">
            <strong>Warning:</strong> Changing your public key will require your user key to be re-activated by another
            user. You will be unable to retrieve any secrets until your key has been reactivated.
        </div>
    {% endif %}
    <form action="." method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            {% render_field form.public_key %}
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-sm-6 col-md-6">
                    <button type="button" class="btn btn-info" id="generate_keypair">Generate a New Key Pair</button>
                </div>
                <div class="col-sm-6 col-md-6 text-right">
                    <button type="submit" name="_update" class="btn btn-primary">Save</button>
                    <a href="{% url 'user:userkey' %}" class="btn btn-default">Cancel</a>
                </div>
            </div>
        </div>
    </form>
    <div class="modal fade" id="new_keypair_modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-md" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="new_keypair_modal_title">
                        New RSA Key Pair
                    </h4>
                </div>
                <div class="modal-body">
                    <strong>New Public Key</strong>
                    <div class="form-group">
                        <textarea class="form-control" id="new_pubkey" style="height: 250px;"></textarea>
                    </div>
                    <strong>New Private Key</strong>
                    <div class="form-group">
                        <textarea class="form-control" id="new_privkey" style="height: 250px;"></textarea>
                    </div>
                </div>
                <div class="modal-footer text-center">
                    <button type="button" class="btn btn-danger" id="use_new_pubkey" data-dismiss="modal">I have saved my new private key</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
<script src="{% static 'js/secrets.js' %}?v{{ settings.VERSION }}"></script>
{% endblock %}